theme: jekyll-theme-architect

url: https://brianmiller.github.io/chili-assistant/
title: Chili Assistant
subtitle: Hook your OOLER into Home Assistant
author: Chili Assistant
simple_search: https://www.google.com/search
description: >-
        <style="font-size: 75%;">Hook your ChiliSleep</style><a style="font-size: 50%;>&trade;</a> <style="font-size: 75%;">OOLER Sleep System</style><style="font-size: 50%;>&trade;</style> <style="font-size: 75%;">into Home Assistant</style>
