theme: jekyll-theme-architect

url: https://brianmiller.github.io/chili-assistant/
title: Chili Assistant
subtitle: Hook your OOLER into Home Assistant
author: Chili Assistant
simple_search: https://www.google.com/search
description: >-
        <p style="font-size: 75%;">Hook your ChiliSleep&trade; OOLER Sleep System&trade; into Home Assistant</p>
