theme: jekyll-theme-architect

url: https://brianmiller.github.io/chili-assistant/
title: Chili Assistant
subtitle: Hook your OOLER into Home Assistant
author: Chili Assistant
simple_search: https://www.google.com/search
description: >-
        <label style="font-size: 75%;">Hook your ChiliSleep</label><label style="font-size: 50%;">&trade;</label><label style="font-size: 75%;"> OOLER Sleep System</label><label style="font-size: 50%;">&trade;</label><label style="font-size: 75%;"> into Home Assistant</label>
