theme: jekyll-theme-architect

url: https://brianmiller.github.io/chili-assistant/
title: Chili Assistant
subtitle: Hook your OOLER into Home Assistant
author: Chili Assistant
simple_search: https://www.google.com/search
description: >-
        <label style="font-size: 65%;">Hook your</label> <a class="custom_style4" href="https://www.chilisleep.com" target="_blank">ChiliSleep</a><label style="font-size: 35%;">&trade;</label><label style="font-size: 65%;"> OOLER Sleep System</label><label style="font-size: 35%;">&trade;</label><label style="font-size: 65%;"> into Home Assistant</label>
        <br>
        <label class="custom_style1">*Chili Assistant is just for fun and not affiliated with</label><a href="https://www.chilisleep.com" target="_blank" class="custom_style2"> ChiliSleep</a><label class="custom_style3">&trade;</label>
